// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"data-flow/internal/biz"
	"data-flow/internal/conf"
	"data-flow/internal/data"
	"data-flow/internal/server"
	"data-flow/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	itemRepo := data.NewSourceRepo(dataData, logger)
	sinkService := biz.NewSinkService(itemRepo, logger)
	dataServiceManager := service.NewDataServiceManager(sinkService, logger)
	configServiceManager := service.NewConfigService(logger)
	grpcServer := server.NewGRPCServer(confServer, dataServiceManager, configServiceManager, logger)
	httpServer := server.NewHTTPServer(confServer, dataServiceManager, configServiceManager, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
