// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: v1/sink/sink.proto

package sink

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 爬虫数据存储
type DoSinkRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SinkId string                 `protobuf:"bytes,1,opt,name=sinkId,proto3" json:"sinkId,omitempty"`
	// 元数据隐藏在data里面
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoSinkRequest) Reset() {
	*x = DoSinkRequest{}
	mi := &file_v1_sink_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoSinkRequest) ProtoMessage() {}

func (x *DoSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sink_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoSinkRequest.ProtoReflect.Descriptor instead.
func (*DoSinkRequest) Descriptor() ([]byte, []int) {
	return file_v1_sink_sink_proto_rawDescGZIP(), []int{0}
}

func (x *DoSinkRequest) GetSinkId() string {
	if x != nil {
		return x.SinkId
	}
	return ""
}

func (x *DoSinkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_v1_sink_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sink_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_v1_sink_sink_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_v1_sink_sink_proto protoreflect.FileDescriptor

const file_v1_sink_sink_proto_rawDesc = "" +
	"\n" +
	"\x12v1/sink/sink.proto\x12\vapi.v1.sink\x1a\x1cgoogle/api/annotations.proto\";\n" +
	"\rDoSinkRequest\x12\x16\n" +
	"\x06sinkId\x18\x01 \x01(\tR\x06sinkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2Z\n" +
	"\aDataHub\x12O\n" +
	"\x06DoSink\x12\x1a.api.v1.sink.DoSinkRequest\x1a\x15.api.v1.sink.Response\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/sink(\x01B-Z+github.com/tomeai/dataflow/api/v1/sink;sinkb\x06proto3"

var (
	file_v1_sink_sink_proto_rawDescOnce sync.Once
	file_v1_sink_sink_proto_rawDescData []byte
)

func file_v1_sink_sink_proto_rawDescGZIP() []byte {
	file_v1_sink_sink_proto_rawDescOnce.Do(func() {
		file_v1_sink_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_sink_sink_proto_rawDesc), len(file_v1_sink_sink_proto_rawDesc)))
	})
	return file_v1_sink_sink_proto_rawDescData
}

var file_v1_sink_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_sink_sink_proto_goTypes = []any{
	(*DoSinkRequest)(nil), // 0: api.v1.sink.DoSinkRequest
	(*Response)(nil),      // 1: api.v1.sink.Response
}
var file_v1_sink_sink_proto_depIdxs = []int32{
	0, // 0: api.v1.sink.DataHub.DoSink:input_type -> api.v1.sink.DoSinkRequest
	1, // 1: api.v1.sink.DataHub.DoSink:output_type -> api.v1.sink.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_sink_sink_proto_init() }
func file_v1_sink_sink_proto_init() {
	if File_v1_sink_sink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_sink_sink_proto_rawDesc), len(file_v1_sink_sink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_sink_sink_proto_goTypes,
		DependencyIndexes: file_v1_sink_sink_proto_depIdxs,
		MessageInfos:      file_v1_sink_sink_proto_msgTypes,
	}.Build()
	File_v1_sink_sink_proto = out.File
	file_v1_sink_sink_proto_goTypes = nil
	file_v1_sink_sink_proto_depIdxs = nil
}
