// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: v1/config/config.proto

package config

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSourceRequest) Reset() {
	*x = UpdateSourceRequest{}
	mi := &file_v1_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSourceRequest) ProtoMessage() {}

func (x *UpdateSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSourceRequest) Descriptor() ([]byte, []int) {
	return file_v1_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateSourceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UpdateSourceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpdateSourceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateSourceRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceResponse) Reset() {
	*x = SourceResponse{}
	mi := &file_v1_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceResponse) ProtoMessage() {}

func (x *SourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceResponse.ProtoReflect.Descriptor instead.
func (*SourceResponse) Descriptor() ([]byte, []int) {
	return file_v1_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *SourceResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SourceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSourceRequest) Reset() {
	*x = AddSourceRequest{}
	mi := &file_v1_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSourceRequest) ProtoMessage() {}

func (x *AddSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSourceRequest.ProtoReflect.Descriptor instead.
func (*AddSourceRequest) Descriptor() ([]byte, []int) {
	return file_v1_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *AddSourceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AddSourceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddSourceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddSourceRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 创建sink，返回sink_id
type CreateSinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 数据库名称
	DnName string `protobuf:"bytes,2,opt,name=dnName,proto3" json:"dnName,omitempty"`
	// 表名
	TableName string `protobuf:"bytes,3,opt,name=tableName,proto3" json:"tableName,omitempty"`
	// source源
	SourceId int32 `protobuf:"varint,4,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	// 备注
	Remark        string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSinkRequest) Reset() {
	*x = CreateSinkRequest{}
	mi := &file_v1_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSinkRequest) ProtoMessage() {}

func (x *CreateSinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSinkRequest.ProtoReflect.Descriptor instead.
func (*CreateSinkRequest) Descriptor() ([]byte, []int) {
	return file_v1_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSinkRequest) GetDnName() string {
	if x != nil {
		return x.DnName
	}
	return ""
}

func (x *CreateSinkRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CreateSinkRequest) GetSourceId() int32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *CreateSinkRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateSinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSinkResponse) Reset() {
	*x = CreateSinkResponse{}
	mi := &file_v1_config_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSinkResponse) ProtoMessage() {}

func (x *CreateSinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_config_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSinkResponse.ProtoReflect.Descriptor instead.
func (*CreateSinkResponse) Descriptor() ([]byte, []int) {
	return file_v1_config_config_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSinkResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_v1_config_config_proto protoreflect.FileDescriptor

const file_v1_config_config_proto_rawDesc = "" +
	"\n" +
	"\x16v1/config/config.proto\x12\rapi.v1.config\x1a\x1cgoogle/api/annotations.proto\"u\n" +
	"\x13UpdateSourceRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"2\n" +
	"\x0eSourceResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"r\n" +
	"\x10AddSourceRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x91\x01\n" +
	"\x11CreateSinkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06dnName\x18\x02 \x01(\tR\x06dnName\x12\x1c\n" +
	"\ttableName\x18\x03 \x01(\tR\ttableName\x12\x1a\n" +
	"\bsourceId\x18\x04 \x01(\x05R\bsourceId\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\",\n" +
	"\x12CreateSinkResponse\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\tR\x06taskId2\xa4\x02\n" +
	"\tConfigHub\x12S\n" +
	"\fUpdateSource\x12\".api.v1.config.UpdateSourceRequest\x1a\x1d.api.v1.config.SourceResponse\"\x00\x12M\n" +
	"\tAddSource\x12\x1f.api.v1.config.AddSourceRequest\x1a\x1d.api.v1.config.SourceResponse\"\x00\x12s\n" +
	"\n" +
	"CreateSink\x12 .api.v1.config.CreateSinkRequest\x1a!.api.v1.config.CreateSinkResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/dataflow/sink/create2\n" +
	"\n" +
	"\bTemplateB1Z/github.com/tomeai/dataflow/api/v1/config;configb\x06proto3"

var (
	file_v1_config_config_proto_rawDescOnce sync.Once
	file_v1_config_config_proto_rawDescData []byte
)

func file_v1_config_config_proto_rawDescGZIP() []byte {
	file_v1_config_config_proto_rawDescOnce.Do(func() {
		file_v1_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_config_config_proto_rawDesc), len(file_v1_config_config_proto_rawDesc)))
	})
	return file_v1_config_config_proto_rawDescData
}

var file_v1_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_config_config_proto_goTypes = []any{
	(*UpdateSourceRequest)(nil), // 0: api.v1.config.UpdateSourceRequest
	(*SourceResponse)(nil),      // 1: api.v1.config.SourceResponse
	(*AddSourceRequest)(nil),    // 2: api.v1.config.AddSourceRequest
	(*CreateSinkRequest)(nil),   // 3: api.v1.config.CreateSinkRequest
	(*CreateSinkResponse)(nil),  // 4: api.v1.config.CreateSinkResponse
}
var file_v1_config_config_proto_depIdxs = []int32{
	0, // 0: api.v1.config.ConfigHub.UpdateSource:input_type -> api.v1.config.UpdateSourceRequest
	2, // 1: api.v1.config.ConfigHub.AddSource:input_type -> api.v1.config.AddSourceRequest
	3, // 2: api.v1.config.ConfigHub.CreateSink:input_type -> api.v1.config.CreateSinkRequest
	1, // 3: api.v1.config.ConfigHub.UpdateSource:output_type -> api.v1.config.SourceResponse
	1, // 4: api.v1.config.ConfigHub.AddSource:output_type -> api.v1.config.SourceResponse
	4, // 5: api.v1.config.ConfigHub.CreateSink:output_type -> api.v1.config.CreateSinkResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_config_config_proto_init() }
func file_v1_config_config_proto_init() {
	if File_v1_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_config_config_proto_rawDesc), len(file_v1_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_config_config_proto_goTypes,
		DependencyIndexes: file_v1_config_config_proto_depIdxs,
		MessageInfos:      file_v1_config_config_proto_msgTypes,
	}.Build()
	File_v1_config_config_proto = out.File
	file_v1_config_config_proto_goTypes = nil
	file_v1_config_config_proto_depIdxs = nil
}
